package hashtable;

import java.util.HashMap;
import java.util.Map;

/**
 * #389
 * Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.
 * @author Ryan
 *
 */
public class FindTheDifference {

	public char findTheDifference(String s, String t) {
		char c = 0;
		Map<Character, Integer> map1 = new HashMap<Character, Integer>();
		Map<Character, Integer> map2 = new HashMap<Character, Integer>();
		for (int i = 0; i < s.length(); i++) {
			if (map1.containsKey(s.charAt(i))) {
				map1.put(s.charAt(i), map1.get(s.charAt(i))+1);
			} else {
				map1.put(s.charAt(i), 1);
			}
		}

		for (int i = 0; i < t.length(); i++) {
			if (map2.containsKey(t.charAt(i))) {
				map2.put(t.charAt(i), map2.get(t.charAt(i))+1);
			} else {
				map2.put(t.charAt(i), 1);
			}
		}

		for (int i = 0; i < t.length(); i++) {
			if (!map1.containsKey(t.charAt(i))) {
				c = t.charAt(i);
			} else {
				if (map2.get(t.charAt(i)) > map1.get(t.charAt(i))) {
					c = t.charAt(i);
				}
			}
		}
		return c;
	}

	public static void main(String[] args) {
		FindTheDifference f = new FindTheDifference();
		String s = "abcdd";
		String t = "dddabc";
		System.out.println(f.findTheDifference(s, t));
	}

}
